### ISSUE TITLE
Add login with Facebook.

### ISSUE THREAD

**Issue by nakul-19** [DSC-JSS-NOIDA/Plasma-Donor-App#63]
**Is your feature request related to a problem? Please describe.**
There is no option to login with Facebook.

**Describe the solution you'd like**
Login with Facebook should be added.

**Comment by karan7393065010** [comment]
Can I work on this issue @nakul-19 .

**Comment by karan7393065010** [comment]
I am having issues with  fetching data .
So you can assign it to another one.

**Comment by sumit619sharma** [comment]
Hii, can i work on this issue @nakul-19

**Comment by plazzy99** [comment]
@sumit619sharma go-ahead 👍🏻

**Comment by sumit619sharma** [comment]
Hi, I m not able to connect app with firebase, it shows  gradle build issue. I resync all the gradle dependencies still it shows error.
![20201224_154230 1](https://user-images.githubusercontent.com/72352873/103133959-6cbd0b80-4662-11eb-8f44-0361214dbe82.jpg)

**Comment by sumit619sharma** [comment]
we are not able to  login app even with google Sign In. It shows Login Failed 10

**Comment by sumit619sharma** [comment]
plz help me I stuck here , I tried all the way to connect with firebase but still nothing happened. I know the later steps of this issue but i stuck here and can't do anything

**Comment by AnubhavPabby** [comment]
Can You Assign me this issue so that I can work on it during Gssoc?

**Comment by kunal299** [comment]
@nakul-19 Can u plz assign this issue to me as a part of Gssoc.

**Comment by nakul-19** [comment]
@sumit619sharma may be this could be of help : https://stackoverflow.com/questions/45279479/error-could-not-parse-the-android-application-modules-gradle-config .

**Comment by AnubhavPabby** [comment]
@nakul-19

-  Is your organization registered on Facebook developers site (https://developers.facebook.com/?no_redirect=1) ?  Because it is mentioned in facebook docs (https://developers.facebook.com/docs/facebook-login/android)
- Because if not first you have to register there with proper details of your app 
- And then provide me following details
   - App id for this Project (https://developers.facebook.com/docs/facebook-login/android#manifest)
   - App Secret Key for this Project

**Comment by AnubhavPabby** [comment]
Also is there any slack or discord channel of this organization where I can communicate with you people
